# What happen to inventory on death, possible values:
# DEFAULT : Minecraft default
# TOTEM : CLEAR + totem
# CLEAR : Clear inventory on death
# KEEP : Keep inventory on death
inventoryOnDeath: DEFAULT