# What happens to inventory on death, possible values:
# DEFAULT : Minecraft default
# TOTEM : CLEAR + totem
# CLEAR : Clear inventory on death
# KEEP : Keep inventory on death
inventoryOnDeath: DEFAULT

# Should the craft for custom totem be enabled.
# You can replace the craft using a datapack or a command. cf plugin readme
enableTotemCraft: true

# Should the death scoreboard be enabled
enableDeathCount: true
