name: Build_And_Deploy_On_Tag

on:
  push:
    tags:
      - v*.*.*

jobs:
  BumpVersion:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: ChangeVersion
        run: |
          sed -i "s/version = \"\(.*\)\"/version = \"${{github.ref_name}}\"/" ./build.gradle.kts

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m ":bookmark: : Bump version in build.gradle"

      - name: Push changes
        uses: ad-m/github-push-action@v1.3.0
        with:
          branch: main

  Assemble:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build -Pversion="${{github.ref_name}}"

      - name: Create release
        uses: ncipollo/release-action@v1.21.0
        with:
          artifacts: "build/libs/*.jar,build/resourcePack/*.jar"
          allowUpdates: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: true